# Generated by Django 3.0.7 on 2020-09-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
